package:
    name: postgresql-client
    version: 9.5.21

source:
  url: http://ftp.postgresql.org/pub/source/v9.5.21/postgresql-9.5.21.tar.gz
  md5: c1a99f2d17b6de1f305fef9d9f6d2235
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - paste = paste:main
    #
    # Would create an entry point called paste that calls paste.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
    build:
        - {{ compiler('c') }}
    host:
        - openssl 1.0
        - gettext
        - readline 6.2
        - zlib
    run:
        - libpq

#outputs:
#     - name: libpq
#        files:
#        - lib/libpq.so 
#        - lib/libpq.so.*

about:
  home: http://www.postgresql.org
  license: PostgreSQL License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
