package:
    name: postgresql-client
    version: 11.7

source:
  url: http://ftp.postgresql.org/pub/source/v11.7/postgresql-11.7.tar.gz
  md5: abb131b13e3183fcc1449f4dbd1a0f2c

requirements:
    build:
        - {{ compiler('c') }}
        - pkg-config
    host:
        - openssl {{ openssl }}
        - libedit {{ libedit }}
        - zlib {{ zlib }}
    run:
        - libpq
        - libedit {{ libedit }}
        - openssl {{ openssl }}

about:
  home: http://www.postgresql.org
  license: PostgreSQL License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
